import Songs from "@/components/Songs";

export const metadata = {
  title: "Music App | Serach",
  description: "Music App Generated by create next app",
};

const SongsPage = () => {
  return (
    <>
      <Songs />
    </>
  );
};

export default SongsPage;
